### ISSUE TITLE
weight initialization?

### ISSUE THREAD

**Issue by dreamhua82** [YingqianWang/LF-DFnet#3]
Hi, the paper said that LF-DFNet used the Kaiming method to initialize other parts of the network. But I can't find the code?

**Comment by YingqianWang** [comment]
'Kaiming_uniform' is the default initialization method in PyTorch.
![微信图片_20210410114035](https://user-images.githubusercontent.com/31008389/114257296-9d4a6a80-99f1-11eb-8c17-832571fd033d.png)
