### ISSUE TITLE
Error on import DCN2

### ISSUE THREAD

**Issue by duongvinh** [YingqianWang/LF-DFnet#5]
Thanks for sharing your great work!

When I compile the DCN in Window 10, it seems to successfully, as follow:
Installed c:\users\my\.conda\envs\lfdfnet\lib\site-packages\dcn2-2.0-py3.7-win-amd64.egg
Processing dependencies for DCN2==2.0
Finished processing dependencies for DCN2==2.0

However, when I try to do the "test.py" or "traning.py", it has the error as follow:
File "f:\1.Data\LF-DFnet-master\code\dcn\functions\deform_conv_func.py", line 13, in <module>
    import DCN2
ImportError: DLL load failed: The specified procedure could not be found.

I am installed same the envs and library as described in the paper. Can you tell me which part am I wrong? I tried to fixed it but no success. 

Thank you.

**Comment by YingqianWang** [comment]
We followed the pipeline and implementation details in our D3Dnet. You can refer to https://github.com/XinyiYing/D3Dnet for details of compiling DCNv2, and ask questions to Xinyi if needed.
