### ISSUE TITLE
Questions about overlapped regions handling in the testing phrase.

### ISSUE THREAD

**Issue by Aithusa1113** [YingqianWang/LF-DFnet#7]
Hi, 
I find that in your code, the testing full resolution LF image is cropped into patches, and the network performs SR on patch level and then merged them to integrate a full LF image.  But the overlapped regions covered by surrounding patches are not averaged or weighted summed to merge a full LF. I wonder if it is a good choice to not average the overlapped regions for the merging of LF? When testing a single image/video, we always choose to average or weighted sum the overlapped regions.

Looking forward to your reply!

**Comment by YingqianWang** [comment]
Yes, it may be a better choice to enhance the final SR performance.
